### PR TITLE
Fixes #515 - Make it work with Django 4.1

### LINKED ISSUE #515: Not working with Django 4.1
Django has removed de installed property from the Model Options object (_meta). And will produce the following error when using Django Activity Stream

`AttributeError: 'Options' object has no attribute 'installed'` this comes from `actstream/registry.py` line 60 (version 1.4.1).

See this commit from Django https://github.com/django/django/commit/8e3b1cf098018b4632de63c359ef6d761e92ec04

### PR DESCRIPTION
**Pull request by marcusaram**
Easy fix, Django has removed the installed property, but they check if app_config is not None. Took over that check.

### CODE REVIEW

File: actstream/registry.py [hunk 1]
```diff
@@ -57,7 +57,7 @@ def is_installed(model_class):
     Returns True if a model_class is installed.
```
Comment (auvipy) [inline actstream/registry.py:57]: comments should also be adjusted, i think

Comment (marcusaram) [reply actstream/registry.py:57]: That part is still correct. The method will return True is the model class is installed in Django. If the app is not in the INSTALLED_APPS of Django this will return False. That is also the behavior before.
