### ISSUE TITLE
Not compatible with django 2.1

### ISSUE THREAD

**Issue by pupattan** [justquick/django-activity-stream#400]
remote:        Traceback (most recent call last):
remote:          File "manage.py", line 23, in <module>
remote:            execute_from_command_line(sys.argv)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
remote:            utility.execute()
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
remote:            django.setup()
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
remote:            apps.populate(settings.INSTALLED_APPS)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
remote:            app_config.import_models()
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
remote:            self.models_module = import_module(models_module_name)
remote:          File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
remote:            return _bootstrap._gcd_import(name[level:], package, level)
remote:          File "<frozen importlib._bootstrap>", line 994, in _gcd_import
remote:          File "<frozen importlib._bootstrap>", line 971, in _find_and_load
remote:          File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
remote:          File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
remote:          File "<frozen importlib._bootstrap_external>", line 678, in exec_module
remote:          File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/actstream/models.py", line 57, in <module>
remote:            class Action(models.Model):
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/actstream/models.py", line 171, in Action
remote:            @models.permalink
remote:        AttributeError: module 'django.db.models' has no attribute 'permalink'

**Comment by auvipy** [comment]
please install from master branch which is compatible with django 2.1

**Comment by pupattan** [comment]
i am installing the latest version 0.6.5 using pip and same is not working.
Could you please let me know the latest version to use ?

**Comment by pupattan** [comment]
It works fine on django **2.0** NOT on **2.1**

**Comment by auvipy** [comment]
i am telling you to install from github master. not the 0.6.5 from pypi. lots of changes occured on github master since the release of 6.5

**Comment by pupattan** [comment]
Thanks for the update.
I will be installing from github master.
Please try to provide through pypi also.
Thanks again

**Comment by auvipy** [comment]
I pinged Justin but he didn't replied. The library is compatible with django 2.1 from long ago in the master
