### ISSUE TITLE
Action.objects.none() doesn't work in Django 2.0.x

### ISSUE THREAD

**Issue by tapia** [justquick/django-activity-stream#393]
If I try to make an empty Queryset like this:

    Action.objects.none()

I get this error:

    TypeError: _clone() got an unexpected keyword argument 'klass'

This is because in Django 2, `QuerySet._clone()` doesn't receive any parameter. I've monkey-patched `GFKQuerySet` like this, and it works nicely:

    def none(self):
        clone = self._clone()
        if hasattr(clone.query, 'set_empty'):
            clone.query.set_empty()
        return clone
    
    GFKQuerySet.none = none

**Comment by tapia** [comment]
No, I didn't, I used the version available from pip (0.6.5).

**Comment by auvipy** [comment]
you should try master and report again
